import { useState, type FormEvent } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { API_BASE_URL, updateProfile } from './api';
import { Heading, Resource, Empty, useResource } from './ui';
import { money, date } from './format';
import type { Session } from './types';
import { applicationStatus, applicationsPath, selectTrades, profilePayload, type Application, type Trade, type Bid, type GroupedShares, type EditableProfile } from './activity-contracts';

export function Applications({ session }: { session: Session }) {
  const resource = useResource<Application[]>(applicationsPath(session.user.id));
  const [params] = useSearchParams(); const propertyId = params.get('propertyId');
  const [status, setStatus] = useState('');
  return <><Heading title="Investment Applications" description="Requested and approved investments, with the latest available status."/><Resource resource={resource}>{data => {
    const rows = data.filter(a => (!propertyId || a.propertyId === propertyId) && (!status || applicationStatus(a.status) === status)).sort((a,b) => Date.parse(b.createdAt)-Date.parse(a.createdAt));
    return <><div className="filters"><label>Status<select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(data.map(a => applicationStatus(a.status)))].map(s => <option key={s}>{s}</option>)}</select></label>{propertyId && <Link to="/applications">Show all properties</Link>}</div>{rows.length ? <div className="property-grid">{rows.map(a => <article className="panel" key={a.id}><span className="tag">{applicationStatus(a.status)}</span><h2><Link to={`/properties/${encodeURIComponent(a.propertyId)}`}>{a.propertyTitle}</Link></h2><dl><dt>Requested amount</dt><dd>{money(a.requestedAmount)}</dd><dt>Requested shares</dt><dd>{a.requestedShares}</dd><dt>Created</dt><dd>{date(a.createdAt)}</dd></dl><details><summary>Application details</summary><dl><dt>Approved amount</dt><dd>{money(a.approvedAmount)}</dd><dt>Approved shares</dt><dd>{a.approvedShares ?? '—'}</dd><dt>Step</dt><dd>{a.stepNumber}</dd><dt>Priority</dt><dd>{a.isPriority ? 'Yes' : 'No'}</dd><dt>Application ID</dt><dd className="identifier">{a.id}</dd></dl></details></article>)}</div> : <Empty title="No matching applications"/>}</>;
  }}</Resource></>;
}
export function TradeHistory({ session }: { session: Session }) {
  const resource = useResource<Trade[]>('/share-offers/transactions'); const [side,setSide] = useState<'buy'|'sell'|'all'>('buy');
  return <><Heading title="Trade History" description="Recent marketplace trades. The API returns up to 200 records; this is not a complete account statement."/><div className="filters"><label>View<select value={side} onChange={e => setSide(e.target.value as typeof side)}><option value="buy">My purchases</option><option value="sell">My sales</option><option value="all">{session.isDemo ? 'All my demo trades' : 'All marketplace trades'}</option></select></label></div><Resource resource={resource}>{data => { const rows=selectTrades(data,session.user.id,side); return rows.length ? <div className="property-grid">{rows.map((t,i) => <article className="panel" key={`${t.timestamp}-${i}`}><h2><Link to={`/properties/${encodeURIComponent(t.propertyId)}`}>{t.propertyTitle}</Link></h2><dl><dt>Date</dt><dd>{date(t.timestamp)}</dd><dt>Shares</dt><dd>{t.shares}</dd><dt>Price / share</dt><dd>{money(t.pricePerShare)}</dd><dt>Total</dt><dd>{money(t.shares*t.pricePerShare)}</dd></dl></article>)}</div> : <Empty title="No matching trades"/>; }}</Resource></>;
}
export function OfferBids({ session }: { session: Session }) {
 const {offerId=''}=useParams(); const resource=useResource<Bid[]>(`/share-offers/${encodeURIComponent(offerId)}/bids`);
 return <><Link to="/marketplace">← Marketplace</Link><Heading title="Marketplace bids" description="Bidding needs backend account security corrections. Accept Bid has no active backend contract."/><Resource resource={resource}>{data => data.length ? <div className="property-grid">{data.map(b=><article className="panel" key={b.id}><h2>{b.bidderId===session.user.id?'Your bid':'Bid'}</h2><dl><dt>Shares</dt><dd>{b.shares}</dd><dt>Price / share</dt><dd>{money(b.bidPricePerShare)}</dd><dt>Date</dt><dd>{date(b.createdAt)}</dd></dl></article>)}</div>:<Empty title="No bids yet"/>}</Resource></>;
}
export function SellShares({session}:{session:Session}) {
 const resource=useResource<GroupedShares[]>(`/share-offers/user/${encodeURIComponent(session.user.id)}/grouped`);
 return <><Heading title="Sell My Shares" description="Review your holdings before listing shares."/><p className="note">Creating listings and selling shares are disabled pending backend account security corrections.</p>{session.isDemo && <p className="demo-banner">Platform buyback has no isolated demo platform wallet. Demo listing is disabled pending blocked/deleted account checks.</p>}<Resource resource={resource}>{data=>data.length?<div className="property-grid">{data.map(s=><article className="panel" key={s.propertyId}><h2><Link to={`/properties/${encodeURIComponent(s.propertyId)}`}>{s.propertyTitle}</Link></h2><dl><dt>Shares</dt><dd>{s.shares}</dd><dt>Total invested</dt><dd>{money(s.totalInvested)}</dd><dt>Average price</dt><dd>{money(s.averagePrice)}</dd>{!session.isDemo && <><dt>Buyback price / share</dt><dd>{money(s.buybackPricePerShare)}</dd></>}</dl></article>)}</div>:<Empty title="No shares available"/>}</Resource></>;
}
function ProfileForm({initial,session}:{initial:EditableProfile;session:Session}) {
 const [profile,setProfile]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function submit(e:FormEvent) { e.preventDefault(); if(busy)return;setBusy(true);setError('');setMessage('');try{await updateProfile(session,profilePayload(profile,initial.email,session.isDemo));setMessage('Profile updated.');}catch(e){setError(e instanceof Error?e.message:'Unable to save profile.');}finally{setBusy(false);} }
 return <form className="panel account-form" onSubmit={submit}><fieldset disabled={busy}>{(['fullName','email','phoneNumber','address'] as const).map((field,i)=><label key={field}>{['Full name','Email','Phone number','Address'][i]}<input type={field==='email'?'email':field==='phoneNumber'?'tel':'text'} value={profile[field]||''} disabled={field==='email'&&session.isDemo} onChange={e=>setProfile({...profile,[field]:e.target.value})}/></label>)}{session.isDemo&&<p className="note">Demo login email is issued by an administrator and cannot be changed here.</p>}<button className="button" disabled={busy}>{busy?'Saving…':'Save profile'}</button></fieldset>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</form>;
}
export function EditProfile({session}:{session:Session}) {const resource=useResource<EditableProfile>(`/users/${encodeURIComponent(session.user.id)}`);return <><Heading title="Edit Profile" description="Update your contact details."/><Resource resource={resource}>{data=><ProfileForm initial={data} session={session}/>}</Resource></>;}
export function ChangePassword({session}:{session:Session}) {return <><Heading title="Change Password" description="Password changes are currently unavailable on the web."/><p className="note">The existing password-change service needs a security correction before this form can be enabled. Please contact support for help with your {session.isDemo?'demo ':''}account.</p><Link to="/support">Contact support →</Link></>;}
export function LegalPage({kind}:{kind:'privacy'|'terms'|'support'}) {const title={privacy:'Privacy Policy',terms:'Terms of Use',support:'Support'}[kind];return <><Heading title={title} description={kind==='support'?'Get help from OwnersClub.':'Read the current document provided by OwnersClub.'}/><section className="panel"><a className="button" href={`${API_BASE_URL.replace(/\/api$/,'')}/${kind}`} target="_blank" rel="noopener noreferrer">Open {title} ↗</a></section></>;}


