import { DemoTopUp } from './financial-ui';
import { financialPolicy } from './financial-contracts';
import { useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { communityWrite } from './api';
import { Heading, Resource, Empty, Metric, useResource } from './ui';
import { money, date } from './format';
import type { Session } from './types';
import { communityPaths, fee, invitePayload, messagePayload, type OwnedProperty, type ClubInfo, type ClubTotals, type Invite, type Withdrawal, type ChatMessage } from './community-contracts';

export function MyProperties({session}:{session:Session}) {
  const resource=useResource<OwnedProperty[]>(communityPaths(session.user.id).properties);
  return <><Heading title="My Properties" description="Your investments grouped by property."/><Link to="/investments">Investment records →</Link><Resource resource={resource}>{rows=>rows.length?<div className="property-grid">{rows.map(row=><article className="panel" key={row.propertyId}><h2><Link to={`/properties/${encodeURIComponent(row.propertyId)}`}>{row.propertyTitle}</Link></h2><dl><dt>Total shares</dt><dd>{row.totalShares}</dd><dt>Total invested</dt><dd>{money(row.totalInvested)}</dd></dl><Link to={`/properties/${encodeURIComponent(row.propertyId)}/payment-plans`}>Payment Plan →</Link></article>)}</div>:<Empty title="No properties yet"/>}</Resource></>;
}
export function Club({session}:{session:Session}) {
  const club=useResource<ClubInfo>(communityPaths(session.user.id).club), totals=useResource<ClubTotals>(communityPaths(session.user.id).totals);
  return <><Heading title="Club status & fees" description="Your current status and fee values supplied by OwnersClub."/><nav className="actions"><Link to="/finance">Assets & history</Link><Link to="/referrals">Invite a friend</Link></nav><Resource resource={club}>{c=><section className="panel"><span className="tag">{c.status || 'Status unavailable'}</span><Metric label="Total assets" value={money(c.totalAssets)}/><dl><dt>Standard marketplace profit fee</dt><dd>{fee(c.baseFee)}</dd><dt>Fee with referral</dt><dd>{fee(c.withReferralFee)}</dd><dt>Invitation availability</dt><dd>{c.canInvite===true?'Available':c.canInvite===false?'Unavailable':'Not provided'}</dd><dt>Referrer reward</dt><dd>{fee(c.referrerRewardPercent)}</dd><dt>Reward duration (years)</dt><dd>{c.referrerRewardYears ?? 'Unavailable'}</dd></dl></section>}</Resource><Resource resource={totals}>{t=><section className="panel"><h2>Your applied fee</h2><dl><dt>Current marketplace profit fee</dt><dd>{fee(t.clubFeePercent)}</dd><dt>Referral linked</dt><dd>{typeof t.hasReferrer==='boolean'?(t.hasReferrer?'Yes':'No'):'Unavailable'}</dd></dl></section>}</Resource></>;
}
export function Referrals({session}:{session:Session}) {
  const club=useResource<ClubInfo>(communityPaths(session.user.id).club), history=useResource<Invite[]>('/referrals/my-invites');
  const [receipt,setReceipt]=useState<{code?:string;link?:string}>({});
  const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''); const lock=useRef(false);
  async function submit(e:FormEvent) {e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const result=await communityWrite(session,'invite',invitePayload(session.isDemo,club.data?.canInvite===true,email)) as {code?:unknown;link?:unknown}|undefined;setReceipt({code:typeof result?.code==='string'?result.code:undefined,link:typeof result?.link==='string'?result.link:undefined});setEmail('');setNotice('Invitation sent.');history.retry();}catch(e){setError(e instanceof Error?e.message:'Unable to send invitation.');}finally{lock.current=false;setBusy(false);}}
  return <><Heading title="Invite a friend" description="Review referral benefits and your invitation history."/><Link to="/club">Club status & fees →</Link><Resource resource={club}>{c=><p className="note">Friend’s marketplace profit fee: {fee(c.withReferralFee)}. Standard fee: {fee(c.baseFee)}. Referrer reward: {fee(c.referrerRewardPercent)} for {c.referrerRewardYears ?? '—'} years.</p>}</Resource>{session.isDemo?<p className="demo-banner">Demo invitations are read-only. No email will be sent.</p>:<form className="panel account-form" onSubmit={submit}><label>Friend’s email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><p>This sends an invitation email to your friend.</p><button className="button" disabled={busy||club.data?.canInvite!==true}>{busy?'Sending…':'Send invitation'}</button>{club.data?.canInvite===false&&<p>Invitations are currently unavailable for your account.</p>}</form>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error} Delivery may be uncertain after a connection error; check history before retrying.</p>}{(receipt.code||receipt.link)&&<section className="panel"><h2>Your invitation</h2>{receipt.code&&<p className="identifier">Code: {receipt.code}</p>}{receipt.link&&<p className="identifier">Link: {receipt.link}</p>}</section>}<h2>Invitation history</h2><Resource resource={history}>{rows=>rows.length?<div className="property-grid">{rows.map(r=><article className="panel" key={r.id}><h3>{r.inviteeEmail}</h3><span className="tag">{r.status}</span><dl><dt>Created</dt><dd>{date(r.createdAt)}</dd><dt>Expires</dt><dd>{date(r.expiresAt)}</dd><dt>Accepted</dt><dd>{date(r.acceptedAt)}</dd></dl></article>)}</div>:<Empty title="No invitations yet"/>}</Resource></>;
}
export function Withdrawals({session}:{session:Session}) {
 const resource=useResource<Withdrawal[]>(communityPaths(session.user.id).withdrawals);
 return <><Heading title="Withdrawal requests" description="Review existing requests and their status."/><Link to="/withdraw">Withdrawal information →</Link>{session.isDemo&&<p className="demo-banner">Demo withdrawals are simulated and never enter the production approval queue.</p>}<Resource resource={resource}>{rows=>rows.length?<div className="property-grid">{[...rows].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).map(r=><article className="panel" key={r.id}><h2>{money(r.amount)}</h2><span className="tag">{r.status}</span><p>{date(r.createdAt)}</p></article>)}</div>:<Empty title="No withdrawal requests"/>}</Resource></>;
}
export function MoneyInfo({session,withdraw=false}:{session:Session;withdraw?:boolean}) {return <><Heading title={withdraw?'Withdraw funds':'Top up'} description="Information about moving funds."/><section className="panel"><p>{session.isDemo?'Demo funds are virtual. No bank, card or payment provider is used.':'Real money transfers are unavailable in this iteration.'}</p>{session.isDemo&&!withdraw?<DemoTopUp key={`${session.user.id}-${session.demoCode}`} session={session}/>:<p>{withdraw?financialPolicy.withdraw:financialPolicy.topup}</p>}<nav className="actions"><Link to="/withdrawals">Withdrawal requests</Link><Link to="/finance">Assets & history</Link><Link to="/transactions">Transactions</Link></nav></section></>;}
export function Chat({session}:{session:Session}) {return session.isDemo?<><Heading title="Support chat" description="Live support chat is disabled in Demo Mode."/><p className="demo-banner">Messages are not sent to production support from sandbox accounts.</p></>:<LiveChat session={session}/>;}
function LiveChat({session}:{session:Session}) {const admin=useResource<{adminId:string}>('/users/admin-id');return <><Heading title="Support chat" description="Send a text message to OwnersClub support. Refresh to check for replies."/><Resource resource={admin}>{a=>a.adminId?<Conversation session={session} adminId={a.adminId}/>:<Empty title="Support is currently unavailable"/>}</Resource></>;}
function Conversation({session,adminId}:{session:Session;adminId:string}) {
 const resource=useResource<ChatMessage[]>(`/chat/conversation/${encodeURIComponent(session.user.id)}/${encodeURIComponent(adminId)}`);const [content,setContent]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const lock=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await communityWrite(session,'chat',messagePayload(session.isDemo,adminId,content));setContent('');setNotice('Message sent.');resource.retry();}catch(e){setError(e instanceof Error?e.message:'Unable to send.');}finally{lock.current=false;setBusy(false);}}
 return <><button onClick={resource.retry}>Refresh conversation</button><Resource resource={resource}>{rows=>rows.length?<section className="message-list panel">{[...rows].sort((a,b)=>Date.parse(a.sentAt)-Date.parse(b.sentAt)).map(m=><article key={m.id}><strong>{m.senderId===session.user.id?'You':'Support'}</strong><p className="preserve-lines">{m.content}</p><small>{date(m.sentAt)}</small></article>)}</section>:<Empty title="No messages yet"/>}</Resource><form className="panel account-form" onSubmit={submit}><label>Message<textarea required value={content} onChange={e=>setContent(e.target.value)} disabled={busy}/></label><button className="button" disabled={busy||!content.trim()||resource.data===undefined}>{busy?'Sending…':'Send message'}</button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error} Check the conversation before retrying if delivery is uncertain.</p>}</>;
}
export function About(){return <><Heading title="About OwnersClub" description="Your property portfolio and account activity in one place."/><section className="panel"><h2>Getting started</h2><p>Sign in with your mobile account, explore properties and follow your investments, rental income and account notifications.</p><p>Demo accounts use virtual funds. Only simulated demo top-ups are available on the web.</p><nav className="actions"><Link to="/login">Open your account</Link><Link to="/login?demo=1">Demo sign-in</Link><Link to="/terms">Terms of Use</Link><Link to="/privacy">Privacy Policy</Link><Link to="/support">Support</Link></nav></section></>;}


