import { financialPolicy } from './financial-contracts';
import { mapLink } from './community-contracts';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { date, imageUrl, money, safeLink } from './format';
import { Empty, Heading, Metric, Resource, useResource } from './ui';
import type { Holding, Investment, Property, PropertyImage, Session, ShareOffer, Totals, Transaction } from './types';

export function Dashboard({ session }: { session: Session }) {
  const totals = useResource<Totals>(`/users/${encodeURIComponent(session.user.id)}/total-assets`);
  const holdings = useResource<Holding[]>(`/investments/with-aggregated/${encodeURIComponent(session.user.id)}`);
  return <><Heading title={`Welcome${session.user.fullName ? `, ${session.user.fullName}` : ' back'}`} description="Your investment overview, all in one place."/><section className="panel quick-actions" aria-labelledby="quick-actions-title"><h2 id="quick-actions-title">Quick Actions</h2><nav aria-label="Quick actions">{[['/properties', 'Explore properties'], ['/marketplace', 'Browse marketplace'], ['/transactions', 'View transactions'], ['/profile', 'Your profile']].map(([to, label]) => <Link key={to} to={to}>{label}<span aria-hidden="true">→</span></Link>)}</nav></section><Resource resource={totals}>{data => <div className="metrics"><Metric label="Total assets" value={money(data.totalAssets)}/><Metric label="Wallet balance" value={money(data.walletBalance)}/><Metric label="Investment value" value={money(data.investmentValue)}/><Metric label="Rental income" value={money(data.rentalIncome)}/><Metric label="Pending applications" value={money(data.pendingApplicationsValue)}/><Metric label="On the marketplace" value={money(data.marketValue)}/></div>}</Resource><section className="panel"><div className="section-heading"><h2>Your portfolio</h2><Link to="/investments">Investment history →</Link></div><Resource resource={holdings}>{data => data.length ? <div className="table-wrap"><table><thead><tr><th>Property</th><th>Shares</th><th>Invested</th><th>Share value</th><th>Ownership</th></tr></thead><tbody>{data.map(item => <tr key={item.propertyId}><td><Link to={`/properties/${item.propertyId}`}>{item.propertyTitle || 'View property'}</Link></td><td>{item.totalShares}</td><td>{money(item.totalInvested)}</td><td>{money(item.totalShareValue)}</td><td>{item.ownershipPercent == null ? '—' : `${item.ownershipPercent.toFixed(2)}%`}</td></tr>)}</tbody></table></div> : <Empty title="Your portfolio starts here">Explore available properties to discover investment opportunities.</Empty>}</Resource></section><Link className="button" to="/properties">Explore properties</Link></>;
}
function PropertyCard({ property: p }: { property: Property }) {
  const source = imageUrl(p.imageBase64);
  return <article className="property-card">{source && <img src={source} alt="" loading="lazy" onError={e => { e.currentTarget.hidden = true; }}/>}<div className="card-content"><div className="row"><span className="tag">{p.listingType || 'Property'}</span><span className="muted">{p.status}</span></div><h2><Link to={`/properties/${p.id}`}>{p.title}</Link></h2><p className="muted">{p.location}</p><span className="muted">Property price</span><strong className="property-price">{money(p.price)}</strong><dl className="card-stats"><dt>Price per share</dt><dd>{p.totalShares > 0 ? money(p.price / p.totalShares) : '—'}</dd></dl><div className="row card-footer"><span>{p.availableShares} shares available</span><Link className="button secondary" aria-label={`View ${p.title}`} to={`/properties/${p.id}`}>Details →</Link></div></div></article>;
}
export function Properties() {
  const resource = useResource<Property[]>('/properties');
  const [search, setSearch] = useState(''), [type, setType] = useState(''), [available, setAvailable] = useState(false);
  return <><Heading title="Properties" description="Explore the OwnersClub property collection."/><Resource resource={resource}>{data => {
    const filtered = [...data].filter(p => `${p.title} ${p.location}`.toLowerCase().includes(search.toLowerCase()) && (!type || p.listingType === type) && (!available || p.availableShares > 0)).sort((a, b) => a.title.localeCompare(b.title));
    return <><div className="filters"><label className="search">Search<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Property or location" type="search"/></label><label>Listing type<select value={type} onChange={e => setType(e.target.value)}><option value="">All types</option>{[...new Set(data.map(p => p.listingType))].filter(Boolean).map(t => <option key={t}>{t}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={available} onChange={e => setAvailable(e.target.checked)}/>Available shares only</label></div><p className="muted" aria-live="polite">{filtered.length} properties</p>{filtered.length ? <div className="property-grid">{filtered.map(p => <PropertyCard key={p.id} property={p}/>)}</div> : <Empty title={data.length ? 'No matching properties' : 'No properties available'}>Try another search or check back later.</Empty>}</>;
  }}</Resource></>;
}
function Gallery({ id }: { id: string }) {
  const images = useResource<PropertyImage[]>(`/properties/${encodeURIComponent(id)}/images`);
  return <Resource resource={images}>{data => data.length ? <div className="gallery">{data.map(img => { const src = imageUrl(img.base64Data); return src ? <img key={img.id} src={src} alt="Property view" loading="lazy"/> : null; })}</div> : <p className="muted">No property images available.</p>}</Resource>;
}
export function PropertyDetails() {
  const { id } = useParams();
  // The mobile screen also finds a property in GET /properties; no assumed detail endpoint.
  const resource = useResource<Property[]>('/properties');
  return <><Link className="back-link" to="/properties">← All properties</Link><Resource resource={resource}>{data => {
    const p = data.find(item => item.id === id);
    if (!p) return <Empty title="Property not found">This property is no longer available.</Empty>;
    const pdf = safeLink(p.presentationPdfUrl);
    return <><Heading title={p.title} description={p.location}><span className="tag">{p.status || p.listingType}</span></Heading><div className="detail-grid"><section className="panel"><Gallery id={p.id}/><h2>Location</h2><p>{p.location || 'Location not provided'}</p>{mapLink(p.latitude,p.longitude) ? <a href={mapLink(p.latitude,p.longitude)!} target="_blank" rel="noopener noreferrer">Open in OpenStreetMap ↗</a> : <p className="muted">Map coordinates are not available.</p>}<h2>About this property</h2><p className="preserve-lines">{p.about || 'A description has not been provided yet.'}</p>{p.expectedYieldText && <><h3>Expected yield</h3><p>{p.expectedYieldText}</p></>}{pdf && <a href={pdf} target="_blank" rel="noopener noreferrer">{p.presentationPdfName || 'View presentation'} ↗</a>}</section><aside className="panel"><h2>Property overview</h2><p className="note">{financialPolicy.purchase}</p><Link to={`/properties/${encodeURIComponent(p.id)}/payment-plans`}>Payment Plan →</Link><dl><dt>Property price</dt><dd>{money(p.price)}</dd><dt>Price per share</dt><dd>{p.totalShares > 0 ? money(p.price / p.totalShares) : '—'}</dd><dt>Available shares</dt><dd>{p.availableShares} / {p.totalShares}</dd><dt>Listing type</dt><dd>{p.listingType}</dd><dt>Expected completion</dt><dd>{date(p.expectedCompletionDate)}</dd><dt>Planned sale</dt><dd>{date(p.plannedSaleDate)}</dd></dl><Link to="/marketplace">View marketplace →</Link></aside></div></>;
  }}</Resource></>;
}
export function Investments({ session }: { session: Session }) {
  const resource = useResource<Investment[]>(`/investments/user/${encodeURIComponent(session.user.id)}`);
  const properties = useResource<Property[]>('/properties');
  const [minShares, setMinShares] = useState(''), [minAmount, setMinAmount] = useState('');
  return <><Heading title="My investments" description="Your investment records and share purchases."/><nav className="actions"><Link to="/my-properties">My Properties</Link><Link to="/applications">Investment Applications →</Link></nav><div className="filters"><label>Minimum shares<input type="number" min="0" value={minShares} onChange={e => setMinShares(e.target.value)}/></label><label>Minimum invested (USD)<input type="number" min="0" value={minAmount} onChange={e => setMinAmount(e.target.value)}/></label></div>{properties.error && <p className="note">Property names could not be loaded. Records below use property IDs. <button className="text-button" onClick={properties.retry}>Retry names</button></p>}<Resource resource={resource}>{data => {
    const rows = [...data].filter(i => i.shares >= (Number(minShares) || 0) && i.investedAmount >= (Number(minAmount) || 0)).sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));
    return rows.length ? <section className="panel table-wrap"><table><thead><tr><th>Property</th><th>Shares</th><th>Invested</th><th>Date</th></tr></thead><tbody>{rows.map(i => <tr key={i.id}><td><Link to={`/properties/${i.propertyId}`}>{properties.data?.find(p => p.id === i.propertyId)?.title || i.propertyId}</Link><small><Link to={`/properties/${encodeURIComponent(i.propertyId)}/payment-plans`}>Payment Plan</Link></small></td><td>{i.shares}</td><td>{money(i.investedAmount)}</td><td>{date(i.createdAt)}</td></tr>)}</tbody></table></section> : <Empty title={data.length ? 'No matching investments' : 'No investments yet'}>Your investment records will appear here.</Empty>;
  }}</Resource></>;
}
export function Marketplace({ session }: { session: Session }) {
  const resource = useResource<ShareOffer[]>('/share-offers/active');
  const [search, setSearch] = useState(''), [mine, setMine] = useState(false);
  return <><Heading title="Marketplace" description="Browse active offers from other investors."/><nav className="actions" aria-label="Marketplace pages"><Link to="/trade-history">Trade History</Link><Link to="/sell-shares">Sell My Shares</Link></nav><div className="filters"><label className="search">Search<input type="search" placeholder="Property name" value={search} onChange={e => setSearch(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={mine} onChange={e => setMine(e.target.checked)}/>My offers only</label></div><p className="note">Buying, bidding and managing offers are disabled pending backend account security corrections.</p><Resource resource={resource}>{data => {
    const rows = data.filter(o => o.isActive && Date.parse(o.expirationDate) > Date.now() && (!mine || o.sellerId === session.user.id) && (o.propertyTitle || '').toLowerCase().includes(search.toLowerCase()));
    return rows.length ? <div className="property-grid">{rows.map(o => <article key={o.id} className="panel offer-card"><span className="tag">{o.sellerId === session.user.id ? 'Your offer' : 'Share offer'}</span><h2><Link to={`/properties/${o.propertyId}`}>{o.propertyTitle || 'View property'}</Link></h2><dl><dt>Shares for sale</dt><dd>{o.sharesForSale}</dd><dt>Starting price / share</dt><dd>{money(o.startPricePerShare)}</dd><dt>Buyout price / share</dt><dd>{money(o.buyoutPricePerShare)}</dd><dt>Expires</dt><dd>{date(o.expirationDate)}</dd></dl><Link className="button secondary" to={`/properties/${o.propertyId}`}>View property →</Link><Link to={`/marketplace/${encodeURIComponent(o.id)}/bids`}>View bids →</Link></article>)}</div> : <Empty title="No matching active offers">New offers will appear here when investors list shares.</Empty>;
  }}</Resource></>;
}
export function Transactions({ session }: { session: Session }) {
  const resource = useResource<Transaction[]>(`/users/transactions/user/${encodeURIComponent(session.user.id)}`);
  const [type, setType] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState('');
  return <><Heading title="Transactions" description="Review your account activity and investment history."/><Resource resource={resource}>{data => {
    const invalid = Boolean(from && to && from > to);
    const rows = [...data].filter(t => (!type || t.type === type) && (!from || Date.parse(t.timestamp) >= new Date(`${from}T00:00:00`).getTime()) && (!to || Date.parse(t.timestamp) <= new Date(`${to}T23:59:59.999`).getTime())).sort((a, b) => Date.parse(b.timestamp) - Date.parse(a.timestamp));
    return <><div className="filters"><label>Type<select value={type} onChange={e => setType(e.target.value)}><option value="">All transactions</option>{[...new Set(data.map(t => t.type))].map(t => <option key={t}>{t}</option>)}</select></label><label>From<input type="date" value={from} onChange={e => setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e => setTo(e.target.value)}/></label></div>{invalid ? <p role="alert" className="error">The end date must be on or after the start date.</p> : rows.length ? <section className="panel table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Property / notes</th><th>Amount (USD)</th><th>Shares</th></tr></thead><tbody>{rows.map(t => <tr key={t.id}><td>{date(t.timestamp)}</td><td><span className="tag neutral">{t.type}</span></td><td>{t.propertyId ? <Link to={`/properties/${t.propertyId}`}>{t.propertyTitle || 'View property'}</Link> : t.propertyTitle || '—'}{t.notes && <small>{t.notes}</small>}</td><td>{money(t.amount)}</td><td>{t.shares ?? '—'}</td></tr>)}</tbody></table></section> : <Empty title="No matching transactions">Try adjusting the filters, or check back after your next transaction.</Empty>}</>;
  }}</Resource></>;
}
export function Profile({ session }: { session: Session }) {
  const resource = useResource<Totals>(`/users/${encodeURIComponent(session.user.id)}/total-assets`);
  // /auth/me queries production Users only. Session metadata works for both account types.
  return <><Heading title="Profile" description="Your account and session details."/><nav className="actions" aria-label="Account settings"><Link to="/club">Club status & fees</Link><Link to="/referrals">Invite a friend</Link><Link to="/chat">Support chat</Link><Link to="/about">About</Link><Link to="/profile/edit">Edit Profile</Link><Link to="/profile/change-password">Change Password</Link><Link to="/support">Support</Link></nav><div className="detail-grid"><section className="panel"><div className="avatar">{(session.user.fullName || session.user.email || 'O').slice(0, 1).toUpperCase()}</div><h2>{session.user.fullName || 'OwnersClub member'}</h2><dl><dt>Email</dt><dd>{session.user.email || '—'}</dd><dt>Account type</dt><dd>{session.isDemo ? 'Demo account' : 'Investor account'}</dd><dt>Role</dt><dd>{session.user.role || 'user'}</dd><dt>User ID</dt><dd className="identifier">{session.user.id}</dd>{session.demoCode && <><dt>Demo code</dt><dd>{session.demoCode}</dd></>}</dl><p className="note">Account details shown here are from your sign-in session. Open Edit Profile for current contact details.</p></section><section className="panel"><h2>Account balance</h2><Resource resource={resource}>{data => <><Metric label="Wallet balance" value={money(data.walletBalance)}/><Metric label="Total assets" value={money(data.totalAssets)}/></>}</Resource></section></div></>;
}



