import { useRef, useState, type FormEvent } from 'react';
import { accountWrite } from './api';
import type { Session } from './types';
export function PasswordForm({session}:{session:Session}) {
 const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const lock=useRef(false);
 async function submit(e:FormEvent) {e.preventDefault();if(lock.current)return;if(next!==confirm){setNotice('New passwords do not match.');return;}lock.current=true;setBusy(true);setNotice('');try{await accountWrite(session,`/users/${encodeURIComponent(session.user.id)}/change-password`,{currentPassword:current,newPassword:next});setNotice('Password changed. Use the new password next time you sign in.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to change password.');}finally{setCurrent('');setNext('');setConfirm('');setBusy(false);lock.current=false;}}
 return <form className="panel account-form" onSubmit={submit}><fieldset disabled={busy}><label>Current password<input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>New password<input required type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/></label><label>Confirm new password<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="button">{busy?'Saving…':'Change password'}</button></fieldset>{notice&&<p role="status">{notice}</p>}</form>;
}
export function AvatarForm({session}:{session:Session}) {
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const lock=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||!file)return;setNotice('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size===0||file.size>2*1024*1024){setNotice('Choose a JPEG, PNG or WebP image up to 2 MB.');return;}lock.current=true;setBusy(true);try{const base64Image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Unable to read image.'));reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file);});await accountWrite(session,`/users/${encodeURIComponent(session.user.id)}/upload-avatar`,{base64Image});setNotice('Avatar updated. View it on your profile.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to upload avatar.');}finally{setBusy(false);lock.current=false;}}
 return <form className="panel account-form" onSubmit={submit}><h2>Avatar</h2><label>Image (up to 2 MB)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={busy||!file}>{busy?'Uploading…':'Save avatar'}</button>{notice&&<p role="status">{notice}</p>}</form>;
}
