services:
  - type: web
    name: real-estate-backend
    runtime: docker
    plan: free
    repo: https://github.com/LeonidTodorenko/sell-estate
    branch: main
    buildFilter:
      paths:
        - RealEstateInvestment/**
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-cvndo963jp1c738hqong-a.frankfurt-postgres.render.com;Port=5432;Database=realestate_wkn3;Username=postgres1;Password=sH00bbhwC82925C71yDiNIUSy1BmlFk5;Ssl Mode=Require;Trust Server Certificate=true
