services:
  - type: web
    name: real-estate-backend
    runtime: docker
    plan: free
    repo: https://github.com/LeonidTodorenko/sell-estate
    branch: main
    buildFilter:
      paths:
        - Dockerfile
        - .dockerignore
        - RealEstateInvestment/**
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
